### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by rslruiz** [dapple-apple/sl3BatmanProject#1]
Change your proposal to create a Lab experiment manual for this project.

**Comment by dapple-apple** [comment]
Good day Sir,

We have revised our project and compared the performance of our code with that of other authors developing similar functions for editing audio files to achieve stylistic changes. Due to this project being more in line with that of a researched comparison, we would need to follow a more comparative approach and thus not a lab experiment manual. 

Thank you once again!
